version: "3"

services:
  v2ray:
    container_name: v2ray
    image: v2fly/v2fly-core
    command: [v2ray, -config=/etc/v2ray/config.json]
    volumes:
      - ./config.json:/etc/v2ray/config.json
    restart: always
networks:
  default:
    external:
      name: host-network