version: '3'
services:
  caddy:
    image: dukangxu/caddy:2.x.x-hugo
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/srv
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data
      - ./config:/config
      - ./exec:/exec
      - ./log:/var/log
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "1"
networks:
  default:
    external:
      name: host-network