version: "3"

services:
  bookstack:
    container_name: bookstack
    image: linuxserver/bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://example.com
      - DB_HOST=mariadb
      - DB_USER=bookstack
      - DB_PASS=bookstack
      - DB_DATABASE=bookstack
    volumes:
      - ./config:/config
    restart: unless-stopped
networks:
  default:
    external:
      name: host-network