version: '3'
services:
  aria2:
    image: p3terx/aria2-pro
    container_name: aria2
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    volumes:
      - ./downloads:/downloads
      - ./config:/config
    restart: unless-stopped
    environment:
      - RPC_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - SPECIAL_MODE=rclone
networks:
  default:
    external:
      name: host-network