version: "3"

services:
  dokuwiki:
    container_name: dokuwiki
    image: linuxserver/dokuwiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 3091:80
    volumes:
      - ./config:/config
    restart: unless-stopped
networks:
  default:
    external:
      name: host-network